version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: dev.Dockerfile
    environment:
      - MONGODB_CONNECTION_STRING=mongodb://qubitro:qubitro@db/qubitro?authSource=admin
      - MONGODB_DATABASE=qubitro
    volumes:
      - ./:/backend
    ports:
      - "8080:8080"

  db:
    image: mongo:4.4.4
    volumes:
      - ./db-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=qubitro
      - MONGO_INITDB_ROOT_PASSWORD=qubitro
      - MONGO_INITDB_DATABASE=qubitro
    ports:
      - "27017:27017"
