// Code generated by go-swagger; DO NOT EDIT.

package permission

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"assignment-permission/models"
)

// GetPermissionOKCode is the HTTP code returned for type GetPermissionOK
const GetPermissionOKCode int = 200

/*
GetPermissionOK OK

swagger:response getPermissionOK
*/
type GetPermissionOK struct {

	/*
	  In: Body
	*/
	Payload models.PermissionListAll `json:"body,omitempty"`
}

// NewGetPermissionOK creates GetPermissionOK with default headers values
func NewGetPermissionOK() *GetPermissionOK {

	return &GetPermissionOK{}
}

// WithPayload adds the payload to the get permission o k response
func (o *GetPermissionOK) WithPayload(payload models.PermissionListAll) *GetPermissionOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get permission o k response
func (o *GetPermissionOK) SetPayload(payload models.PermissionListAll) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetPermissionOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = models.PermissionListAll{}
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetPermissionInternalServerErrorCode is the HTTP code returned for type GetPermissionInternalServerError
const GetPermissionInternalServerErrorCode int = 500

/*
GetPermissionInternalServerError Internal Server Error

swagger:response getPermissionInternalServerError
*/
type GetPermissionInternalServerError struct {
}

// NewGetPermissionInternalServerError creates GetPermissionInternalServerError with default headers values
func NewGetPermissionInternalServerError() *GetPermissionInternalServerError {

	return &GetPermissionInternalServerError{}
}

// WriteResponse to the client
func (o *GetPermissionInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
