// Code generated by go-swagger; DO NOT EDIT.

package permission

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostPermissionHandlerFunc turns a function with the right signature into a post permission handler
type PostPermissionHandlerFunc func(PostPermissionParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostPermissionHandlerFunc) Handle(params PostPermissionParams) middleware.Responder {
	return fn(params)
}

// PostPermissionHandler interface for that can handle valid post permission params
type PostPermissionHandler interface {
	Handle(PostPermissionParams) middleware.Responder
}

// NewPostPermission creates a new http.Handler for the post permission operation
func NewPostPermission(ctx *middleware.Context, handler PostPermissionHandler) *PostPermission {
	return &PostPermission{Context: ctx, Handler: handler}
}

/*
	PostPermission swagger:route POST /permission Permission postPermission

# Create Permission

Create Permission
*/
type PostPermission struct {
	Context *middleware.Context
	Handler PostPermissionHandler
}

func (o *PostPermission) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostPermissionParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
