// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Qubitro Task",
    "title": "A Permission application",
    "version": "1.0.0"
  },
  "paths": {
    "/": {
      "get": {
        "description": "Health check",
        "tags": [
          "Health"
        ],
        "summary": "Health check",
        "responses": {
          "200": {
            "description": "OK"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      }
    },
    "/permission": {
      "get": {
        "description": "Get Permission",
        "tags": [
          "Permission"
        ],
        "summary": "Get Permission",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/PermissionListAll"
            }
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      },
      "post": {
        "description": "Create Permission",
        "tags": [
          "Permission"
        ],
        "summary": "Create Permission",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/PermissionCreateRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/PermissionCreateSuccessResponse"
            }
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      }
    },
    "/role": {
      "get": {
        "description": "Get Role",
        "tags": [
          "Role"
        ],
        "summary": "Get Role",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/RoleListAllResponse"
            }
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      },
      "post": {
        "description": "Create Role",
        "tags": [
          "Role"
        ],
        "summary": "Create Role",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/RoleCreateRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/RoleCreateSuccessResponse"
            }
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      }
    }
  },
  "definitions": {
    "PermissionCreateRequest": {
      "type": "object",
      "properties": {
        "groups": {
          "type": "array",
          "items": {
            "type": "object"
          },
          "example": [
            {
              "group_id": "group_1_id",
              "members": [
                "user_2_id",
                "user_3_id"
              ],
              "role": "admin"
            }
          ]
        },
        "resource": {
          "type": "string",
          "example": "Resource ID"
        },
        "users": {
          "type": "array",
          "items": {
            "type": "object"
          },
          "example": [
            {
              "role": "admin",
              "user_id": "user_1_id"
            }
          ]
        }
      }
    },
    "PermissionCreateSuccessResponse": {
      "type": "object",
      "properties": {
        "groups": {
          "type": "array",
          "items": {
            "type": "object"
          },
          "example": [
            {
              "group_id": "group_1_id",
              "members": [
                "user_2_id",
                "user_3_id"
              ],
              "role": "admin"
            }
          ]
        },
        "resource": {
          "type": "string",
          "example": "Resource ID"
        },
        "users": {
          "type": "array",
          "items": {
            "type": "object"
          },
          "example": [
            {
              "role": "admin",
              "user_id": "user_1_id"
            }
          ]
        }
      }
    },
    "PermissionListAll": {
      "type": "array",
      "items": {
        "type": "object"
      },
      "example": [
        {
          "groups": [
            {
              "group_id": "group_1_id",
              "members": [
                "user_2_id",
                "user_3_id"
              ],
              "role": "admin"
            }
          ],
          "resource": "Resource ID",
          "users": [
            {
              "role": "admin",
              "user_id": "user_1_id"
            }
          ]
        }
      ]
    },
    "RoleCreateRequest": {
      "type": "object",
      "properties": {
        "_id": {
          "type": "string",
          "example": "Role ID"
        },
        "actions": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "example": [
            "read",
            "write"
          ]
        },
        "description": {
          "type": "string",
          "example": "Role Description"
        },
        "name": {
          "type": "string",
          "example": "Role Name"
        }
      }
    },
    "RoleCreateSuccessResponse": {
      "type": "object",
      "properties": {
        "_id": {
          "type": "string",
          "example": "Role ID"
        },
        "actions": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "example": [
            "read",
            "write"
          ]
        },
        "description": {
          "type": "string",
          "example": "Role Description"
        },
        "name": {
          "type": "string",
          "example": "Role Name"
        }
      }
    },
    "RoleListAllResponse": {
      "type": "array",
      "items": {
        "type": "object"
      },
      "example": [
        {
          "_id": "Role ID",
          "actions": [
            "read",
            "write"
          ],
          "description": "Role Description",
          "name": "Role Name"
        }
      ]
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Qubitro Task",
    "title": "A Permission application",
    "version": "1.0.0"
  },
  "paths": {
    "/": {
      "get": {
        "description": "Health check",
        "tags": [
          "Health"
        ],
        "summary": "Health check",
        "responses": {
          "200": {
            "description": "OK"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      }
    },
    "/permission": {
      "get": {
        "description": "Get Permission",
        "tags": [
          "Permission"
        ],
        "summary": "Get Permission",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/PermissionListAll"
            }
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      },
      "post": {
        "description": "Create Permission",
        "tags": [
          "Permission"
        ],
        "summary": "Create Permission",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/PermissionCreateRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/PermissionCreateSuccessResponse"
            }
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      }
    },
    "/role": {
      "get": {
        "description": "Get Role",
        "tags": [
          "Role"
        ],
        "summary": "Get Role",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/RoleListAllResponse"
            }
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      },
      "post": {
        "description": "Create Role",
        "tags": [
          "Role"
        ],
        "summary": "Create Role",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/RoleCreateRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/RoleCreateSuccessResponse"
            }
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      }
    }
  },
  "definitions": {
    "PermissionCreateRequest": {
      "type": "object",
      "properties": {
        "groups": {
          "type": "array",
          "items": {
            "type": "object"
          },
          "example": [
            {
              "group_id": "group_1_id",
              "members": [
                "user_2_id",
                "user_3_id"
              ],
              "role": "admin"
            }
          ]
        },
        "resource": {
          "type": "string",
          "example": "Resource ID"
        },
        "users": {
          "type": "array",
          "items": {
            "type": "object"
          },
          "example": [
            {
              "role": "admin",
              "user_id": "user_1_id"
            }
          ]
        }
      }
    },
    "PermissionCreateSuccessResponse": {
      "type": "object",
      "properties": {
        "groups": {
          "type": "array",
          "items": {
            "type": "object"
          },
          "example": [
            {
              "group_id": "group_1_id",
              "members": [
                "user_2_id",
                "user_3_id"
              ],
              "role": "admin"
            }
          ]
        },
        "resource": {
          "type": "string",
          "example": "Resource ID"
        },
        "users": {
          "type": "array",
          "items": {
            "type": "object"
          },
          "example": [
            {
              "role": "admin",
              "user_id": "user_1_id"
            }
          ]
        }
      }
    },
    "PermissionListAll": {
      "type": "array",
      "items": {
        "type": "object"
      },
      "example": [
        {
          "groups": [
            {
              "group_id": "group_1_id",
              "members": [
                "user_2_id",
                "user_3_id"
              ],
              "role": "admin"
            }
          ],
          "resource": "Resource ID",
          "users": [
            {
              "role": "admin",
              "user_id": "user_1_id"
            }
          ]
        }
      ]
    },
    "RoleCreateRequest": {
      "type": "object",
      "properties": {
        "_id": {
          "type": "string",
          "example": "Role ID"
        },
        "actions": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "example": [
            "read",
            "write"
          ]
        },
        "description": {
          "type": "string",
          "example": "Role Description"
        },
        "name": {
          "type": "string",
          "example": "Role Name"
        }
      }
    },
    "RoleCreateSuccessResponse": {
      "type": "object",
      "properties": {
        "_id": {
          "type": "string",
          "example": "Role ID"
        },
        "actions": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "example": [
            "read",
            "write"
          ]
        },
        "description": {
          "type": "string",
          "example": "Role Description"
        },
        "name": {
          "type": "string",
          "example": "Role Name"
        }
      }
    },
    "RoleListAllResponse": {
      "type": "array",
      "items": {
        "type": "object"
      },
      "example": [
        {
          "_id": "Role ID",
          "actions": [
            "read",
            "write"
          ],
          "description": "Role Description",
          "name": "Role Name"
        }
      ]
    }
  }
}`))
}
