// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PermissionCreateRequest permission create request
//
// swagger:model PermissionCreateRequest
type PermissionCreateRequest struct {

	// groups
	// Example: [{"group_id":"group_1_id","members":["user_2_id","user_3_id"],"role":"admin"}]
	Groups []interface{} `json:"groups"`

	// resource
	// Example: Resource ID
	Resource string `json:"resource,omitempty"`

	// users
	// Example: [{"role":"admin","user_id":"user_1_id"}]
	Users []interface{} `json:"users"`
}

// Validate validates this permission create request
func (m *PermissionCreateRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this permission create request based on context it is used
func (m *PermissionCreateRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PermissionCreateRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PermissionCreateRequest) UnmarshalBinary(b []byte) error {
	var res PermissionCreateRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
