// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// RoleCreateSuccessResponse role create success response
//
// swagger:model RoleCreateSuccessResponse
type RoleCreateSuccessResponse struct {

	// id
	// Example: Role ID
	ID string `json:"_id,omitempty"`

	// actions
	// Example: ["read","write"]
	Actions []string `json:"actions"`

	// description
	// Example: Role Description
	Description string `json:"description,omitempty"`

	// name
	// Example: Role Name
	Name string `json:"name,omitempty"`
}

// Validate validates this role create success response
func (m *RoleCreateSuccessResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this role create success response based on context it is used
func (m *RoleCreateSuccessResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RoleCreateSuccessResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RoleCreateSuccessResponse) UnmarshalBinary(b []byte) error {
	var res RoleCreateSuccessResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
